vim.cmd.colorscheme("tokyonight")
vim.cmd("hi Directory guibg=NONE")
vim.cmd("hi SignColumn guibg=NONE")
vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
vim.api.nvim_set_hl(0, "LineNr", { bg = "none" })
vim.api.nvim_set_hl(0, "CopilotSuggestion", { fg = "#8a8a8a", force = true })
vim.api.nvim_set_hl(0, '@org.agenda.deadline', { fg = '#FFAAAA' })
vim.api.nvim_set_hl(0, '@org.agenda.scheduled', { fg = '#AAFFAA' })
