vim.g.copilot_filetypes = {
    ["*"] = false,
    ["gitcommit"] = true,
    ["org"] = true,
    ["lua"] = true,
    ["python"] = true,
    ["cpp"] = true,
    ["hpp"] = true,
    ["c"] = true,
    ["h"] = true,
    ["bash"] = true,
    ["sh"] = true,
    ["zsh"] = true,
    ["bazel"] = true,
    ["java"] = true,
    ["javascript"] = true,
    ["typescript"] = true,
    ["go"] = true,
    ["rust"] = true,
    ["robot"] = true,
    ["yaml"] = true,
    ["json"] = true,
}

